test1: test1.c sut.o
	gcc -g -otest1 test1.c sut.o -lpthread

test2: test2.c sut.o
	gcc -g -otest2 test2.c sut.o -lpthread

test3: test3.c sut.o
	gcc -g -otest3 test3.c sut.o -lpthread

test4: test4.c sut.o
	gcc -g -otest4 test4.c sut.o -lpthread

test5: test5.c sut.o
	gcc -g -otest5 test5.c sut.o -lpthread

sut.o: sut.c
	gcc -c -g sut.c

